apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webook-mysql-claim
  namespace: webook
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
