apiVersion: v1
kind: Service
metadata:
  name: webook
  namespace: webook
spec:
  selector:
    app: webook
  type: LoadBalancer
  ports:
  - name: webook
    protocol: TCP
    port: 8080
    targetPort: 8080