apiVersion: v1
kind: Service
metadata:
  name: webook-mysql
  namespace: webook
spec:
  selector:
    app: webook-mysql
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 30006
    protocol: TCP
