apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-local-pv
  namespace: webook
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: "/mnt/data"